version: '3'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  blintr:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blintr
      - JWT_SECRET=your_secure_jwt_secret
      - PORT=8080
    depends_on:
      - mongodb

volumes:
  mongodb_data:
